### ISSUE TITLE
MongoDB reporting "AuthenticationAbandoned: Overridden by new authentication session" for a PHP client

### ISSUE THREAD

**Issue by AlesKrajnik** [10gen-labs/mongo-php-driver-prototype#1506]
### Bug Report

Hi all,

I am observing **AuthenticationAbandoned: Overridden by new authentication session** errors (code **337**) with message **Failed to authenticate** in MongoDB's logs for existing connections from my PHP applications. These errors start to happen after some time for connections that started with **Successfully authenticated**. However, my PHP application connects to the MongoDB server successfully and reports no errors whatsoever.

Some parts of the application run as long-running PHP processes and use MongoDB's `db.collection.watch()`, so, they are connected to MongoDB indefinitely. The errors are being logged for a few different connections. I am not sure, though, whether these errors are produced only by the long-running processes or if it's also the case of the HTTP requests-related connections.

The errors seem to be generated only by a PHP client. I don't have any other PHP application connecting to the server to compare with another PHP application, but I have a Node.js application connecting to the same MongoDB instance and it doesn't produce any such errors.

I can't seem to find any details about the error on Google and the error code is also marked as internal in https://github.com/mongodb/mongo/blob/master/src/mongo/base/error_codes.yml#L421C1-L421C1.

Here's the full log line, please note the empty `user` and `db` fields, even though they are specified in the connection URI:

```json
{
  "t": {
    "$date": "2024-01-03T12:31:37.529+00:00"
  },
  "s": "I",
  "c": "ACCESS",
  "id": 5286307,
  "ctx": "conn704",
  "msg": "Failed to authenticate",
  "attr": {
    "client": "127.0.0.6:35615",
    "isSpeculative": false,
    "isClusterMember": false,
    "mechanism": "",
    "user": "",
    "db": "",
    "error": "AuthenticationAbandoned: Overridden by new authentication session",
    "result": 337,
    "metrics": {
      "conversation_duration": {
        "micros": 96184090,
        "summary": {}
      }
    },
    "extraInfo": {}
  }
}
```

The error message appears in the logs every 60-120 seconds, but only after some time. The connection starts with successful authentication, and only after some time starts producing these errors:

```json
{"t":{"$date":"2024-01-03T12:16:48.551+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn704","msg":"client metadata","attr":{"remote":"127.0.0.6:35615","client":"conn704","doc":{"driver":{"name":"mongoc / ext-mongodb:PHP / PHPLIB/symfony-mongodb ","version":"1.25.2 / 1.17.2 / 1.17.0/2.6.1 "},"os":{"type":"Linux","name":"Alpine Linux","version":"3.19.0","architecture":"x86_64"},"platform":"PHP 8.3.0 cfg=0x03d21ea8f9 posix=200809 stdc=201710 CC=GCC 13.2.1 20231014 CFLAGS=\"\" LDFLAGS=\"\""}}}
{"t":{"$date":"2024-01-03T12:16:48.552+00:00"},"s":"I",  "c":"ACCESS",   "id":6788604, "ctx":"conn704","msg":"Auth metrics report","attr":{"metric":"acquireUser","micros":0}}
{"t":{"$date":"2024-01-03T12:16:48.623+00:00"},"s":"I",  "c":"ACCESS",   "id":5286306, "ctx":"conn704","msg":"Successfully authenticated","attr":{"client":"127.0.0.6:35615","isSpeculative":true,"isClusterMember":false,"mechanism":"SCRAM-SHA-256","user":"user","db":"db","result":0,"metrics":{"conversation_duration":{"micros":71886,"summary":{"0":{"step":1,"step_total":2,"duration_micros":153},"1":{"step":2,"step_total":2,"duration_micros":39}}}},"extraInfo":{}}}
{"t":{"$date":"2024-01-03T12:16:48.626+00:00"},"s":"I",  "c":"NETWORK",  "id":6788700, "ctx":"conn704","msg":"Received first command on ingress connection since session start or auth handshake","attr":{"elapsedMillis":2}}
{"t":{"$date":"2024-01-03T12:19:06.016+00:00"},"s":"I",  "c":"ACCESS",   "id":5286307, "ctx":"conn704","msg":"Failed to authenticate","attr":{"client":"127.0.0.6:35615","isSpeculative":false,"isClusterMember":false,"mechanism":"","user":"","db":"","error":"AuthenticationAbandoned: Overridden by new authentication session","result":337,"metrics":{"conversation_duration":{"micros":66309991,"summary":{}}},"extraInfo":{}}}
{"t":{"$date":"2024-01-03T12:20:07.549+00:00"},"s":"I",  "c":"ACCESS",   "id":5286307, "ctx":"conn704","msg":"Failed to authenticate","attr":{"client":"127.0.0.6:35615","isSpeculative":false,"isClusterMember":false,"mechanism":"","user":"","db":"","error":"AuthenticationAbandoned: Overridden by new authentication session","result":337,"metrics":{"conversation_duration":{"micros":61532898,"summary":{}}},"extraInfo":{}}}
{"t":{"$date":"2024-01-03T12:21:44.741+00:00"},"s":"I",  "c":"ACCESS",   "id":5286307, "ctx":"conn704","msg":"Failed to authenticate","attr":{"client":"127.0.0.6:35615","isSpeculative":false,"isClusterMember":false,"mechanism":"","user":"","db":"","error":"AuthenticationAbandoned: Overridden by new authentication session","result":337,"metrics":{"conversation_duration":{"micros":97191948,"summary":{}}},"extraInfo":{}}}
{"t":{"$date":"2024-01-03T12:22:49.899+00:00"},"s":"I",  "c":"ACCESS",   "id":5286307, "ctx":"conn704","msg":"Failed to authenticate","attr":{"client":"127.0.0.6:35615","isSpeculative":false,"isClusterMember":false,"mechanism":"","user":"","db":"","error":"AuthenticationAbandoned: Overridden by new authentication session","result":337,"metrics":{"conversation_duration":{"micros":65157577,"summary":{}}},"extraInfo":{}}}
```

The field `attr.metrics.conversation_duration.micros` seems to match closely the time difference between two **Failed to authenticate** error messages.

The MongoDB is deployed as a replica set, my connection URI is as follows:

```
mongodb://user:pass@mongodb-internal-0.mongodb-internal.services,mongodb-internal-1.mongodb-internal.services/?authSource=db
```

The details of the connection from MongoDB's `db.currentOp()` output:

```json
[
  {
    "type": "op",
    "host": "mongodb-internal-1:27017",
    "desc": "conn704",
    "connectionId": 704,
    "client": "127.0.0.6:35615",
    "clientMetadata": {
      "driver": {
        "name": "mongoc / ext-mongodb:PHP / PHPLIB/symfony-mongodb",
        "version": "1.25.2 / 1.17.2 / 1.17.0/2.6.1"
      },
      "os": {
        "type": "Linux",
        "name": "Alpine Linux",
        "version": "3.19.0",
        "architecture": "x86_64"
      },
      "platform": "PHP 8.3.0 cfg=0x03d21ea8f9 posix=200809 stdc=201710 CC=GCC 13.2.1 20231014 CFLAGS=\"\" LDFLAGS=\"\""
    },
    "active": false,
    "currentOpTime": "2024-01-03T12:33:35.714+00:00",
    "effectiveUsers": [ { "user": "user", "db": "db" } ],
    "threaded": true
  }
]
```

My application and the MongoDB server are deployed in a Kubernetes cluster extended with istio service mesh, all hosted by DigitalOcean. The IP address `127.0.0.6` in istio is supposed to be used for "undeclared" services ports (as discussed in https://github.com/istio/istio/issues/29603), so the issue might be related to istio. However, since my Node.js application runs in the same infrastructure and uses the same connection URI (with different user, password and db) and does not produce any such errors, it might be that the PHP client is doing something differently.

### Environment

I have the following setup:

* Kubernetes 1.28 hosted by Digital Ocean
* PHP 8.3.0
* MongoDB 7.0.4, deployed as a replica set (using Kubernetes' `StatefulSet`)
* istio 1.20.1

Composer libraries used:

* mongodb/mongodb: 1.17.0
* doctrine/mongodb-odm: 2.6.1

MongoDB's extension configuration:

```
MongoDB support => enabled
MongoDB extension version => 1.17.2
MongoDB extension stability => stable
libbson bundled version => 1.25.2
libmongoc bundled version => 1.25.2
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => enabled
libmongoc SASL => enabled
libmongoc SRV => enabled
libmongoc compression => enabled
libmongoc compression snappy => enabled
libmongoc compression zlib => enabled
libmongoc compression zstd => enabled
libmongocrypt bundled version => 1.8.2
libmongocrypt crypto => enabled
libmongocrypt crypto library => libcrypto
crypt_shared library version => unknown
```

### Expected and Actual Behavior

I would expect the error not to appear in the MongoDB's logs.

**Comment by jmikola** [comment]
I traced the introduction of AuthenticationAbandoned(337) back to [mongodb/mongo@5b83d4c](https://github.com/mongodb/mongo/commit/5b83d4cc18cc0e322912f86c7fba6c14355986e7?diff=split&w=1#diff-9320f07c06c183a21f0abda567c922df0c374ad1bc831b50931f3608492f5b23R61) and [SERVER-52863](https://jira.mongodb.org/browse/SERVER-52863).

> Some parts of the application run as long-running PHP processes and use MongoDB's `db.collection.watch()`, so, they are connected to MongoDB indefinitely. The errors are being logged for a few different connections. I am not sure, though, whether these errors are produced only by the long-running processes or if it's also the case of the HTTP requests-related connections.

If you'd like to further identify the connections, you could look into using the `appName` URI option in either in the connection string or `$uriOptions` parameter to the Manager or Client constructor. The option is discussed in more detail in the [`MongoDB\Driver\Manager::__construct()` docs](https://www.php.net/manual/en/mongodb-driver-manager.construct.php) and should allow you append an identifier to server-side log messages for connections associated with that URI. In this case, you could use `appName` to differentiate the long-running PHP processes from the web app, as well as any connections from Node.js.

I'm not familiar with istio, but as a proxy is it possible that the driver-to-proxy connection is terminating while the proxy-to-server connection is not? In that case, we might see the driver reestablishing a connection and sending the initial auth handshake (as it should); however, the proxy only ends up passing the auth handshake over to the server, where it's unexpected due to there already being an existing auth session.

I'd also like to confirm that there's nothing in istio that would result in multiple driver connections being multiplexed across a single server connection. In other words, can we safely assume that "conn704" in the logs above corresponds to exactly one instance of the PHP driver? If the logs are split across several minutes, I think the likely suspect would be whatever process is watching a change stream (e.g. [`MongoDB\Collection::watch()`](https://www.mongodb.com/docs/php-library/current/reference/method/MongoDBCollection-watch/)).

If you're willing to debug that process further, you could register an SDAM logger within the process and have that log output (to a stream, file, or logging service, whichever you prefer). Using the [sdam_logger.php](https://github.com/mongodb/mongo-php-library/blob/master/examples/sdam_logger.php) example script as a base, you can build upon the subscriber class and replace the `printf()` calls to log to your desired output. Since authentication is performed as part of connection initialization, I would expect the `serverOpening` events to be of particular interest -- but it'd be worth logging all events for review. The log lines in the example script are mostly one-liners, but if you'd like to add additional information from these events you can explore the API reference for the event classes in the [extension documentation](https://www.php.net/manual/en/mongodb.monitoring.php).

**Comment by jmikola** [comment]
@aleshaczech: Thanks for the excellent debugging. I'll investigate this further and follow up once I have something to report. The 60-second delay (I can't speak for 120) corresponds to the single-threaded monitoring interval used in libmongoc, so I'm going to start by looking into whether the outgoing monitoring command is being improperly assembled (e.g. re-using a document previously prepared for the initial handshake).

**Comment by emilushi** [comment]
I am having the same issue on a nodejs application with mongoose. I have a similar setup as @aleshaczech, I have some processes running on background and as well a frontend that makes requests.

Looking at the logs I do see the same notification pop in almost every minute:

```
{"t":{"$date":"2024-02-28T10:16:54.548+00:00"},"s":"I",  "c":"ACCESS",   "id":5286307, "ctx":"conn5","msg":"Failed to authenticate","attr":{"client":"192.168.65.1:29381","isSpeculative":false,"isClusterMember":false,"mechanism":"","user":"","db":"","error":"AuthenticationAbandoned: Overridden by new authentication session","result":337,"metrics":{"conversation_duration":{"micros":60010044,"summary":{}}},"extraInfo":{}}}
```
Adding `authMechanism=SCRAM-SHA-256` to the connection string didn't made the notification go away.
The background processes are running without any interruption and as well the client is able to make requests and connect to mongo successfully. This looks like a session overlap based on the message.

**Comment by alexbevi** [comment]
@emilushi this sounds like something we'd want to investigate. Are you able to share a self-contained reproduction that produces this result? If so you could open a new [ticket in JIRA under the Node project](https://jira.mongodb.org/) so that we can dig into this further.

**Comment by emilushi** [comment]
@alexbevi I will try to create one for you tomorrow.
